@host = localhost:8080
@version = v1

// Generate JWT
POST http://{{host}}/api/{{version}}/token HTTP/1.1
content-type: application/json
    
{
    "email": "john.doe@example.com",
    "password": "abAB13!#"
}
###